# Generated by Django 2.2.16 on 2023-03-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230314_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipepost',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
            preserve_default=False,
        ),
    ]
